CREATE USER egor WITH PASSWORD '123456';

GRANT CONNECT ON DATABASE postgres TO egor;
GRANT USAGE ON SCHEMA kursovaya4sem TO egor;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA kursovaya4sem TO egor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA kursovaya4sem TO egor;

ALTER DEFAULT PRIVILEGES IN SCHEMA kursovaya4sem
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO egor;
ALTER DEFAULT PRIVILEGES IN SCHEMA kursovaya4sem
    GRANT USAGE, SELECT ON SEQUENCES TO egor;
