DO $$
BEGIN
    CREATE USER egor WITH PASSWORD '123456';
EXCEPTION
    WHEN duplicate_object THEN
        ALTER USER egor WITH PASSWORD '123456';
END $$;

GRANT CONNECT ON DATABASE postgres TO egor;
GRANT USAGE ON SCHEMA kursovaya4sem TO egor;

GRANT SELECT ON ALL TABLES IN SCHEMA kursovaya4sem TO egor;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA kursovaya4sem TO egor;

REVOKE INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA kursovaya4sem FROM egor;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA kursovaya4sem TO egor;

ALTER DEFAULT PRIVILEGES IN SCHEMA kursovaya4sem
    GRANT SELECT ON TABLES TO egor;
ALTER DEFAULT PRIVILEGES IN SCHEMA kursovaya4sem
    GRANT USAGE, SELECT ON SEQUENCES TO egor;
ALTER DEFAULT PRIVILEGES IN SCHEMA kursovaya4sem
    GRANT EXECUTE ON FUNCTIONS TO egor;
